#!/usr/bin/env node
// Install AIEOS into Claude Code, machine-wide. Run once per machine.
//
//   npm run setup
//
// It writes two things, both with this install's absolute path and the install date
// baked in, so the kernel/laws resolve correctly from anywhere:
//
//   1. ~/.claude/commands/aieos.md  — the on-demand `/aieos` slash command.
//   2. ~/.claude/CLAUDE.md          — a machine-wide session bootstrap so EVERY Claude
//      Code session, in any folder, starts with AIEOS already guiding the conversation
//      (no need to type /aieos). Written inside AIEOS:BEGIN/END markers so re-running is
//      idempotent and any of your own content in that file is preserved.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const AIEOS_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATE = new Date().toISOString().slice(0, 10);

const CLAUDE_DIR = path.join(os.homedir(), '.claude');
const COMMANDS_DIR = path.join(CLAUDE_DIR, 'commands');
const TARGET = path.join(COMMANDS_DIR, 'aieos.md');
const BOOTSTRAP = path.join(CLAUDE_DIR, 'CLAUDE.md');

const body = `---
description: Acionar o AIEOS em qualquer projeto — roteia a requisição pelo fluxo do Governo (size → council → plan → fan-out → gate → memory → report).
---

<!-- Generated by AIEOS \`npm run setup\` on ${DATE}. Source install: ${AIEOS_ROOT} -->
<!-- Re-run \`npm run setup\` from the AIEOS root to regenerate after moving the install. -->

You are operating **AIEOS** (the AI Enterprise Operating System) to support the project
in the **current working directory**.

**AIEOS install root (fixed, absolute):** \`${AIEOS_ROOT}\`

AIEOS is NOT installed in this project — it is mounted from the path above. Read its law
from there first (do not expect these files in the current project):

- \`${path.join(AIEOS_ROOT, 'CLAUDE.md')}\`
- \`${path.join(AIEOS_ROOT, 'kernel', 'laws', 'prime-directives.md')}\`

If the current project happens to contain its own AIEOS root (subfolder/submodule),
prefer that local one; otherwise use the install root above.

Act as the **Government** and run the request below through the documented flow:

1. **Route** it to the right company (or keep it at the Government for enterprise /
   cross-company work). Companies never talk to each other directly (Directive #5).
2. **Size** it to an Engagement Tier (T0–T4) — see \`kernel/laws/engagement-tiers.md\`.
3. **Discuss before building** (Directive #3): for T2+, convene a council and record
   minutes. Every recorded discussion gets a **mandatory audio summary** (general default).
4. **Plan**, then **fan out** across up to 15 parallel agents with disjoint file
   ownership (Directive #4). The Orchestrator routes; it never implements (Directive #2).
5. **Quality gate**: run the AIEOS conformance check (\`npm test\` from the AIEOS root).
6. **Memory**: update the relevant registers in the AIEOS install.
7. **Report** concisely.

Inherit the kernel; never fork it (Directive #6). To build a new entity, copy the
matching template in \`templates/\` — never invent a bespoke shape.

**Operate per the Operating Doctrine** (\`kernel/laws/operating-doctrine.md\`): bias to
action, decide then offer a one-line off-ramp, carry every task to done, verify then
claim. Be the sharp, high-agency AI that finishes the work.

**Support mode (this is the default for \`/aieos\` outside the AIEOS repo):** when
operating inside ANOTHER project, **create a \`resumo/\` folder at the current project
root** (if it does not already exist) and place each council/decision's **mandatory
audio summary** there; a **PDF report is optional** (write it only if a generator is
available). Do not write to the AIEOS repo's own \`government/decisions/resumo/\` — the
summaries belong to the project being supported.

Request: $ARGUMENTS
`;

fs.mkdirSync(COMMANDS_DIR, { recursive: true });
fs.writeFileSync(TARGET, body, 'utf8');

// 2. Machine-wide session bootstrap (~/.claude/CLAUDE.md), inside markers.
const BEGIN = '<!-- AIEOS:BEGIN (managed by npm run setup — do not edit between markers) -->';
const END = '<!-- AIEOS:END -->';

const aieosBlock = `${BEGIN}
<!-- Generated by AIEOS \`npm run setup\` on ${DATE}. Source install: ${AIEOS_ROOT} -->

# AIEOS — machine-wide operating mode

Every Claude Code session on this machine runs **on top of AIEOS** (the AI Enterprise
Operating System). You are not plain Claude — you are the AIEOS **Government**, guiding
the conversation per the AIEOS doctrine, in whatever project the user is currently in.

**AIEOS install root (fixed, absolute):** \`${AIEOS_ROOT}\`

Before doing substantive work, read the law from the install root (it is not copied into
each project): \`${path.join(AIEOS_ROOT, 'CLAUDE.md')}\` and
\`${path.join(AIEOS_ROOT, 'kernel', 'laws', 'prime-directives.md')}\`.

**How to behave -- FULL PROCESS, OPTIMIZED FOR COST (spend fewer tokens, same rigor):**
Keep the documented flow (route -> size T0-T4 -> council for T2+ -> plan -> fan out ->
quality gate -> memory -> report). Do NOT water down the process to save money; instead
make every step cheaper:
- **Run the fleet on the cheapest capable model.** Sub-agents, council members, searches
  and mechanical edits default to a LIGHTER model (Haiku; Sonnet for harder analysis).
  Reserve the strongest model (Opus) for the final synthesis / hardest decision only. A
  4-member council on a light model costs a fraction of the same council on Opus -- same
  process, far less spend. This is the biggest lever.
- **Terse, structured agent I/O.** Give agents tight briefs and require COMPACT, structured
  conclusions (findings + fix, not essays). Never restate context an agent does not need.
- **Reuse, do not re-derive.** Do not re-read files already in context; pass results between
  steps instead of re-fetching; skip redundant verification of things already proven. Lean
  on prompt caching (keep stable context stable).
- **Parallelize** independent work in one batch -- faster, and lets cheap models do the bulk.
- **Records & audio are for major/strategic decisions (T3+) or when the user asks** -- routine
  work just gets a short report. (This is an artifact choice, not a cut to the reasoning.)
- **Support mode (current folder is NOT the AIEOS repo):** for those major decisions, create a
  \`resumo/\` folder at the **current project root** and put the audio summary there (never in
  the AIEOS repo). A PDF report is optional.
- If the current folder **is** the AIEOS repo (or contains its own AIEOS root), operate on
  AIEOS itself and follow that repo's own CLAUDE.md.
- This machine-wide mode is the ambient default; the \`/aieos <request>\` command still works
  for an explicit, one-off invocation.
${END}`;

let bootstrapContent;
if (fs.existsSync(BOOTSTRAP)) {
  const existing = fs.readFileSync(BOOTSTRAP, 'utf8');
  const re = new RegExp(`${BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`);
  bootstrapContent = re.test(existing)
    ? existing.replace(re, aieosBlock)
    : `${existing.trimEnd()}\n\n${aieosBlock}\n`;
} else {
  bootstrapContent = `${aieosBlock}\n`;
}
fs.writeFileSync(BOOTSTRAP, bootstrapContent, 'utf8');

// 3. Register the autopilot hooks in ~/.claude/settings.json (preserving any others):
//    Stop → capture the session as guarded memory; SessionStart → auto-sync (self-update +
//    guarded memory push). Identified by script name so re-running setup refreshes the paths
//    without duplicating, and `npm run teardown` can remove exactly these.
const SETTINGS = path.join(CLAUDE_DIR, 'settings.json');
let settings = {};
try { settings = JSON.parse(fs.readFileSync(SETTINGS, 'utf8')); } catch { /* none yet */ }
settings.hooks = settings.hooks || {};
function manageHook(event, scriptFile, statusMessage) {
  const command = `node "${path.join(AIEOS_ROOT, 'scripts', scriptFile)}"`;
  const arr = settings.hooks[event] || [];
  const kept = arr.filter((e) => !(Array.isArray(e.hooks) && e.hooks.some((h) => typeof h.command === 'string' && h.command.includes(scriptFile))));
  kept.push({ hooks: [{ type: 'command', command, async: true, statusMessage }] });
  settings.hooks[event] = kept;
}
manageHook('Stop', 'memory-capture.mjs', 'AIEOS: capturando memoria da sessao');
manageHook('SessionStart', 'auto-sync.mjs', 'AIEOS: sincronizando (update + memoria)');
fs.mkdirSync(CLAUDE_DIR, { recursive: true });
fs.writeFileSync(SETTINGS, JSON.stringify(settings, null, 2), 'utf8');

console.log('AIEOS installed machine-wide.');
console.log(`  /aieos command   → ${TARGET}`);
console.log(`  autopilot hooks  → ${SETTINGS} (capture + auto-sync)`);
console.log(`  session bootstrap → ${BOOTSTRAP}`);
console.log(`  AIEOS install root: ${AIEOS_ROOT}`);
console.log(`  Date: ${DATE}`);
console.log('  Every Claude Code session on this machine now starts as AIEOS.');
